#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)
#
# This script will...
# 1- Merge clumped files.
# 2- Read control variants generated by SNPsnap.
# 3- Run plink on control variants to expand control sets.
# 4- Pick random variants in LD with controls.
#
# Run this script with R 4.0.3
#
# Gokberk Alagoz
# created on: 02.06.2021

#####

library(biomaRt)
library(data.table)
options(stringsAsFactors=FALSE)

#--------------------------------------------
# PATHS

#leadSNPlist = "/data/workspaces/lag/workspaces/lg-ukbiobank/projects/enigma_evol/enigma_evo/evolution/results/selection_analysis/european_hemave/working_snps.txt"
CSAregions = "/data/workspaces/lag/workspaces/lg-ukbiobank/projects/enigma_evol/enigma_evo/evolution/results/selection_analysis/european_hemave/CSAregions"
outDir = "/data/workspaces/lag/workspaces/lg-ukbiobank/projects/enigma_evol/enigma_evo/evolution/results/selection_analysis/european_hemave"
resources = "/data/workspaces/lag/workspaces/lg-ukbiobank/projects/enigma_evol/enigma_evo/evolution/resources/"
phylop = "/data/workspaces/lag/workspaces/lg-ukbiobank/projects/enigma_evol/enigma_evo/evolution/resources/primates.phyloP46way.bed"
phastcons = "/data/workspaces/lag/workspaces/lg-ukbiobank/projects/enigma_evol/enigma_evo/evolution/resources/primates.phastCons46way.bed"

#--------------------------------------------
# FUNCTIONS

df2bed = function(CSAregions, outDir) {
  # extracts phyloP and phastCons scores from .bed files
  # for each SNP
  
  for (i in dir(CSAregions, full.names = T)) {
    fileName = sapply(strsplit(i, split = "/"), tail, 1)
    tmp_df = read.table(i)
    tmp_bed = data.frame(chr = character(), 
                         str = character(),
                         end = character(),
                         id = character(),
                         set = character(),
                         stringsAsFactors = F)
    m = 1
        for (j in 1:nrow(tmp_df)){
            for (k in 1:ncol(tmp_df)){
              tmp_bed[m,]$chr = paste0("chr", strsplit(tmp_df[j,k], split = ":")[[1]][1])
              tmp_bed[m,]$str = as.numeric(strsplit(tmp_df[j,k], split = ":")[[1]][2])-1
              tmp_bed[m,]$end = as.numeric(strsplit(tmp_df[j,k], split = ":")[[1]][2])
              tmp_bed[m,]$id = m
              tmp_bed[m,]$set = j
              m = m + 1
              }
        }
    
    # Clear NAs
    tmp_bed = na.omit(tmp_bed)
    
    write.table(tmp_bed, file = paste0(outDir, "/variant_beds/", fileName), 
                quote = F, row.names = F, col.names = F, sep = "\t")
  }
  
}

sort_bed = function(outDir) {
  # This function intersects annotation and variant
  # bed files using bedtools.
  
  for (i in dir(paste0(outDir,"/variant_beds"), full.names = T)) {
    
    fileName = sapply(strsplit(i, split = "/"), tail, 1)
    rsID = strsplit(fileName, split = "\\.")[[1]][1]
    system(paste0("module load bedtools/2.29.2 \
                  sort-bed ", i, " > ", outDir, "/variant_beds/", rsID,
                  ".sorted.bed"))
    tmp = read.table(paste0(outDir, "/variant_beds/", rsID, ".sorted.bed"))
    tmp$V4 = rownames(tmp)
    write.table(tmp, file = paste0(outDir, "/variant_beds/", rsID, ".sorted.bed"), 
                quote = F, row.names = F, col.names = F, sep = "\t")
  }
}

intersect_varBed_vs_annotBed = function(outDir) {
  # This function intersects annotation and variant
  # bed files using bedtools.
  
  for (i in dir(paste0(outDir,"/variant_beds"), full.names = T, pattern = "sorted")) {
      
    fileName = sapply(strsplit(i, split = "/"), tail, 1)
    rsID = strsplit(fileName, split = "\\.")[[1]][1]
    system(paste0("module load bedtools/2.29.2 \
                  bedmap --echo --echo-map-score ", i, " ", phylop,
                  " > ", outDir, "/intersects/", rsID,
                  ".intersect.txt"))
  }
}

#--------------------------------------------
# MAIN

###
# Read in clumped SNPs from all summary stats
# and merge them.
###

#df2bed(CSAregions, outDir)

#--------------------------------------------

sessionInfo()